# Site settings
title: Dellrud
description: "Just a landing page for my main domain"
baseurl: "/"
url: "https://dellrud.se"

# User settings
username: Joakim Dellrud
user_description: I am a IT Technician specializing in everything and anything FOSS.
user_title: DevOps Engineer
email: contact@dellrud.se

exclude: ['package.json', 'src', 'node_modules', 'vendor']
