# Site settings
title: Dellrud
description: "Just a landing page for my main domain"
baseurl: "/"
url: "https://dellrud.se"

# User settings
username: Joakim Dellrud
user_description: Linux enthusiast by day and nerd by night. Also a avid reader and of course love everything Star Wars. Sometimes a cabin dweller, usually found in Sweden.
user_title: DevOps Engineer
email: contact@dellrud.se

exclude: ['package.json', 'src', 'node_modules', 'vendor']
