# Site settings
title: Dellrud
description:
baseurl: "/"
url: "https://dellrud.se"

# User settings
username:
user_description:
user_title:
email: contact@dellrud.se
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
